improve mandatory field visibility
fylein/fyle-intacct-app pull request #52
Opened 2021-07-22 06:15 UTC by NileshPant1999

2021-07-22 06:30 UTC, ashwin1111 requested changes
@NileshPant1999 please do one round of self review and assign it back, have left few comments.

2021-07-22 06:30 UTC, ashwin1111 commented on src/app/si/settings/connect-sage-intacct/connect-sage-intacct.ts
> +    forkJoin(connectSageIntacct).subscribe(responses => {
single api call doesn't need to be a fork join, please change this

2021-07-22 06:30 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.html
> +          <mandatory-field *ngIf="isFieldMandatory('defaultVendor')"></mandatory-field>
`isFieldMandatory('defaultItem') `
Please be very careful on these sections, single name change can be very dangerous

2021-07-22 06:30 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.html
> +      <mandatory-error-message listName="default credit card vendor" *ngIf="form.controls.defaultVendor.touched && !form.controls.defaultVendor.valid"></mandatory-error-message>
`listName` is incorrect, Please be very careful on these sections, single name change can be very dangerous

2021-07-26 13:52 UTC, ashwin1111 requested changes

2021-07-26 13:52 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.defaultReimbursableExpensePaymentType.setValidators(Validators.required);
I don't find this in API

2021-07-26 13:52 UTC, ashwin1111 commented on src/app/si/settings/sage-intacct-configurations/configuration/configuration.component.ts
> +          that.snackBar.open('Auto mapping of employees may take up to 10 minutes');
`Auto mapping of employees may take few minutes`

2021-07-26 14:40 UTC, NileshPant1999 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.defaultReimbursableExpensePaymentType.setValidators(Validators.required);
this is for sage_intacct reimbursement creation you can find it inside mappings/utils.py

2021-07-30 14:43 UTC, ashwin1111 requested changes

2021-07-30 14:43 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.paymentAccount.setValidators(Validators.required);
Will payment account be used for both reimbursements as well as ap payments? If not, do we need anything else as mandatory for one of the payment type?

2021-07-30 14:43 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +      if (that.generalSettings.import_projects) {
Since we depreciated this flag, please modify this condition

2021-07-30 14:43 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +      if (that.generalSettings.import_projects) {
Check this across all apps please

2021-08-02 09:38 UTC, NileshPant1999 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.paymentAccount.setValidators(Validators.required);
yes payment account is used for both ap payment as well as reimbursement

2021-08-02 09:43 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.paymentAccount.setValidators(Validators.required);
Please include it in the condition above. 
`if (that.generalSettings.sync_fyle_to_sage_intacct_payments || other_column) { }`

2021-08-02 09:45 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.paymentAccount.setValidators(Validators.required);
I don't think we use it for reimbursements, please check the whole flow and confirm

2021-08-02 09:50 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.paymentAccount.setValidators(Validators.required);
Please add missing validations in api if you add it here

2021-08-02 10:35 UTC, ashwin1111 commented on src/app/si/settings/general-mappings/general-mappings.component.ts
> +        that.form.controls.paymentAccount.setValidators(Validators.required);
resolved offline

2021-08-02 10:35 UTC, ashwin1111 approved these changes

2021-08-02 12:52 UTC, merged