Email-notification for sage intacct app changes commit
fylein/fyle-intacct-app pull request #93
Opened 2022-04-27 09:42 UTC by DhaaraniCIT

2022-04-27 13:54 UTC, ashwin1111 requested changes

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/core/models/schedule-setting.model.ts
> +  emails_selected: [];
string[];

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/core/models/schedule-setting.model.ts
> +  additional_email_options:[];
string[];

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/core/models/schedule-setting.model.ts
> +  emails_selected: [];
or whatever the db column type is

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/core/models/schedule-setting.model.ts
> +  additional_email_options:[];
or whatever the db column type is

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/shared/simple-search-select/simple-search-select.component.html
> +</form>
new line at the end of file

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/shared/simple-search-select/simple-search-select.component.scss
> +    //     display: flex;
remove dead code

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/si/settings/schedule/schedule.component.html
> +              <a href="https://help.fylehq.com/en/articles/6064944-how-to-be-notified-when-auto-export-fails-in-fyle-netsuite-integration" target="_blank"
kb article link has to be updated

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/si/settings/schedule/add-email-dialog/add-email-dialog.component.html
> +  Add an email address on which you would like to recieve your integration notifcation mails.
`notification` typo

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/si/settings/schedule/add-email-dialog/add-email-dialog.component.html
> +  </mat-dialog-actions>
eof

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/si/settings/schedule/schedule.component.html
> +  <!-- <div class="page-header schedule--header"> -->
remove dead code

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/si/settings/schedule/schedule.component.html
> +          <span class="schedule--header-info">Select the frequancy at which you want your Automated import-export to
`frequency` typo

2022-04-27 13:54 UTC, ashwin1111 commented on src/app/si/settings/schedule/schedule.component.ts
> +  workspaceAdmins = [];
mention type

2022-04-27 15:02 UTC, DhaaraniCIT commented on src/app/si/settings/schedule/schedule.component.html
> +              <a href="https://help.fylehq.com/en/articles/6064944-how-to-be-notified-when-auto-export-fails-in-fyle-netsuite-integration" target="_blank"
what is the link

2022-04-28 06:36 UTC, NileshPant1999 commented on src/app/si/settings/schedule/schedule.component.html
> +              <a href="https://help.fylehq.com/en/articles/6064944-how-to-be-notified-when-auto-export-fails-in-fyle-netsuite-integration" target="_blank"
for now you can comment this out Gayathiri will create a new one and will give you the link.

2022-04-28 06:37 UTC, NileshPant1999 commented on src/app/core/models/schedule-setting.model.ts
> +  additional_email_options: any[];
why any ??

2022-04-28 06:39 UTC, NileshPant1999 commented on src/app/si/settings/schedule/schedule.component.ts
> +  workspaceAdmins: any[] = [];
why any ??

2022-04-28 08:43 UTC, ashwin1111 approved these changes

2022-04-28 09:12 UTC, merged